### ISSUE TITLE
Improve Test Coverage for Cursor to 100%

### ISSUE THREAD

**Issue by msbukkuri** [twitterdev/twitter-ruby-ads-sdk#99]
**Issue Type:** Improvement

**Description:**
Please see details here: https://codeclimate.com/github/twitterdev/twitter-ruby-ads-sdk/coverage/573f548192f8840001031792

**Comment by brandonblack** [comment]
I'd be happy to review any pull requests you have to improve test coverage. Feel free to send them my way when you're ready. 

However, we're never going to target 100% coverage since thats [been proven](https://webmozart.io/blog/2010/03/15/why-not-to-want-100-code-coverage/) [many times](https://medium.com/@mandrigin/a-broken-promise-of-100-d07d2f6de79a#.pimr0lq7w) to be both [unrealistic](http://johnpwood.net/2008/12/30/why-code-coverage-alone-doesnt-mean-squat/) and [harmful](http://www.dan-manges.com/blog/increasing-code-coverage-may-be-harmful) in software projects. The majority of our test code in this project is intended to be integration and behavioral testing. In a project like this, basic unit testing to achieve an arbitrary coverage goals isn't that meaningful.

The test suite in this project [already actively enforces a minimum of 80%](https://github.com/twitterdev/twitter-ruby-ads-sdk/blob/master/spec/spec_helper.rb#L15) to make sure features can't be checked in without adequate coverage. No commits can be made without satisfying that requirement. 100% coverage is always a false sense of security and doesn't guarantee the right tests are being written. It's not a goal worth achieving even if we had ambitious contributors willing to try for it.

**Comment by msbukkuri** [comment]
@brandonblack Apologies - should have checked before creating these tickets. Will send whatever I have when ready.

**Comment by brandonblack** [comment]
@msbukkuri no problem at all. Please do feel free to improve coverage where you see gaps. That kind of pull request is *_always*_ welcome! ❤️
